/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AppSchema extends BaseModel {
  static $columns = ['appstreamContent', 'appstreamId', 'appstreamUrl', 'createdAt', 'desktopContent', 'desktopUrl', 'homepage', 'iconId', 'id', 'license', 'type', 'updatedAt', 'version'] as const
  $columns = AppSchema.$columns
  @column()
  declare appstreamContent: string | null
  @column()
  declare appstreamId: string | null
  @column()
  declare appstreamUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare desktopContent: string | null
  @column()
  declare desktopUrl: string | null
  @column()
  declare homepage: string | null
  @column()
  declare iconId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare license: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: string | null
}

export class AppAliasSchema extends BaseModel {
  static $columns = ['appId', 'appstreamId', 'createdAt', 'id', 'updatedAt'] as const
  $columns = AppAliasSchema.$columns
  @column()
  declare appId: number
  @column()
  declare appstreamId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AppCategorySchema extends BaseModel {
  static $columns = ['appId', 'categoryId', 'createdAt', 'id', 'updatedAt'] as const
  $columns = AppCategorySchema.$columns
  @column()
  declare appId: number
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AppPkgSchema extends BaseModel {
  static $columns = ['appId', 'createdAt', 'id', 'pkgId', 'updatedAt'] as const
  $columns = AppPkgSchema.$columns
  @column()
  declare appId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pkgId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AppPkgNameSchema extends BaseModel {
  static $columns = ['appId', 'createdAt', 'id', 'name', 'type', 'updatedAt'] as const
  $columns = AppPkgNameSchema.$columns
  @column()
  declare appId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AppTranslationSchema extends BaseModel {
  static $columns = ['appId', 'createdAt', 'id', 'locale', 'name', 'summary', 'updatedAt'] as const
  $columns = AppTranslationSchema.$columns
  @column()
  declare appId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare name: string | null
  @column()
  declare summary: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'parentId', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare parentId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DistroSchema extends BaseModel {
  static $columns = ['appCount', 'arch', 'compatibleDistroId', 'createdAt', 'eolDate', 'id', 'name', 'pkgCount', 'pkgType', 'releaseDate', 'updatedAt', 'version'] as const
  $columns = DistroSchema.$columns
  @column()
  declare appCount: number
  @column()
  declare arch: string
  @column()
  declare compatibleDistroId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare eolDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare pkgCount: number
  @column()
  declare pkgType: string | null
  @column.date()
  declare releaseDate: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: string | null
}

export class DistroRepoSchema extends BaseModel {
  static $columns = ['createdAt', 'distroId', 'id', 'repoId', 'updatedAt'] as const
  $columns = DistroRepoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare distroId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare repoId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FavoriteSchema extends BaseModel {
  static $columns = ['appId', 'createdAt', 'id', 'updatedAt', 'userId'] as const
  $columns = FavoriteSchema.$columns
  @column()
  declare appId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ImageSchema extends BaseModel {
  static $columns = ['createdAt', 'format', 'height', 'id', 'path', 'size', 'updatedAt', 'userId', 'width'] as const
  $columns = ImageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare format: string
  @column()
  declare height: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare path: string
  @column()
  declare size: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare width: number
}

export class PkgSchema extends BaseModel {
  static $columns = ['arch', 'checksum', 'checksumType', 'createdAt', 'description', 'downloadUrl', 'id', 'installCommand', 'license', 'name', 'path', 'release', 'repoId', 'size', 'summary', 'type', 'updatedAt', 'userId', 'version'] as const
  $columns = PkgSchema.$columns
  @column()
  declare arch: string | null
  @column()
  declare checksum: string | null
  @column()
  declare checksumType: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare downloadUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare installCommand: string | null
  @column()
  declare license: string | null
  @column()
  declare name: string
  @column()
  declare path: string | null
  @column()
  declare release: string | null
  @column()
  declare repoId: number | null
  @column()
  declare size: number | null
  @column()
  declare summary: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare version: string | null
}

export class PkgDistroSchema extends BaseModel {
  static $columns = ['createdAt', 'distroId', 'id', 'pkgId', 'updatedAt'] as const
  $columns = PkgDistroSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare distroId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pkgId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QueueJobSchema extends BaseModel {
  static $columns = ['acquiredAt', 'data', 'dedupAt', 'dedupId', 'dedupTtl', 'error', 'executeAt', 'finishedAt', 'id', 'queue', 'score', 'status', 'workerId'] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare dedupAt: bigint | number | null
  @column()
  declare dedupId: string | null
  @column()
  declare dedupTtl: bigint | number | null
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'cronExpression', 'everyMs', 'fromDate', 'id', 'lastRunAt', 'name', 'nextRunAt', 'payload', 'runCount', 'runLimit', 'status', 'timezone', 'toDate'] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class RepoSchema extends BaseModel {
  static $columns = ['appCount', 'baseUrl', 'configContent', 'configUrl', 'createdAt', 'id', 'installScript', 'lastSyncedAt', 'name', 'pkgCount', 'source', 'syncIntervalDays', 'type', 'updatedAt'] as const
  $columns = RepoSchema.$columns
  @column()
  declare appCount: number
  @column()
  declare baseUrl: string
  @column()
  declare configContent: string | null
  @column()
  declare configUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare installScript: string | null
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare pkgCount: number
  @column()
  declare source: string
  @column()
  declare syncIntervalDays: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReviewSchema extends BaseModel {
  static $columns = ['appId', 'comment', 'createdAt', 'distroId', 'id', 'locale', 'rating', 'updatedAt', 'userId'] as const
  $columns = ReviewSchema.$columns
  @column()
  declare appId: number
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare distroId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare rating: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarId', 'createdAt', 'distroId', 'email', 'id', 'name', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare distroId: number | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
